title: "Muhammad Ibrahim Khan"
url: "https://ibrahimkhan4real.github.io"
baseurl: ""
markdown: kramdown

# Exclude files from Jekyll processing
exclude:
  - scripts/
  - worker/
  - My_CV.pdf
  - README.md
  - .github/
  - vendor/

# optional: better excerpts
excerpt_separator: "<!--more-->"
